In [25]:
import pandas as pd
from sklearn import preprocessing,cross_validation,svm

/home/ishaan/Softwares/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [26]:
import quandl as qdl

In [27]:
data_csv=pd.read_csv('/home/ishaan/Codes/Datasets/WIKI-PRICES.csv')

In [28]:
data_csv.head(6)

,ticker,date,open,high,low,close,volume,ex-dividend,split_ratio,adj_open,adj_high,adj_low,adj_close,adj_volume
0,A,1999-11-18,45.50,50.00,40.00,44.00,44739900.0,0.0,1.0,31.041951,34.112034,27.289627,30.018590,44739900.0
1,A,1999-11-19,42.94,43.00,39.81,40.38,10897100.0,0.0,1.0,29.295415,29.336350,27.160002,27.548879,10897100.0
2,A,1999-11-22,41.31,44.00,40.06,44.00,4705200.0,0.0,1.0,28.183363,30.018590,27.330562,30.018590,4705200.0
3,A,1999-11-23,42.50,43.63,40.25,40.25,4274400.0,0.0,1.0,28.995229,29.766161,27.460188,27.460188,4274400.0
4,A,1999-11-24,40.13,41.94,40.00,41.06,3464400.0,0.0,1.0,27.378319,28.613174,27.289627,28.012803,3464400.0
5,A,1999-11-26,40.88,41.50,40.75,41.19,1237100.0,0.0,1.0,27.889999,28.312988,27.801308,28.101494,1237100.0

In [29]:
data_csv['h-l_%']=(data_csv['adj_high']-data_csv['adj_low'])/data_csv['adj_low']*100

In [30]:
data_csv['%_chng']=(data_csv['adj_close']-data_csv['adj_open'])/data_csv['adj_open']*100
#percentage change can be neagaive convert o positive

In [31]:
data_csv

,ticker,date,open,high,low,close,volume,ex-dividend,split_ratio,adj_open,adj_high,adj_low,adj_close,adj_volume,h-l_%,%_chng
0,A,1999-11-18,45.50,50.00,40.00,44.00,44739900.0,0.0,1.0,31.041951,34.112034,27.289627,30.018590,44739900.00,25.000000,-3.296703
1,A,1999-11-19,42.94,43.00,39.81,40.38,10897100.0,0.0,1.0,29.295415,29.336350,27.160002,27.548879,10897100.00,8.013062,-5.961807
2,A,1999-11-22,41.31,44.00,40.06,44.00,4705200.0,0.0,1.0,28.183363,30.018590,27.330562,30.018590,4705200.00,9.835247,6.511740
3,A,1999-11-23,42.50,43.63,40.25,40.25,4274400.0,0.0,1.0,28.995229,29.766161,27.460188,27.460188,4274400.00,8.397516,-5.294118
4,A,1999-11-24,40.13,41.94,40.00,41.06,3464400.0,0.0,1.0,27.378319,28.613174,27.289627,28.012803,3464400.00,4.850000,2.317468
5,A,1999-11-26,40.88,41.50,40.75,41.19,1237100.0,0.0,1.0,27.889999,28.312988,27.801308,28.101494,1237100.00,1.840491,0.758317
6,A,1999-11-29,41.00,42.44,40.56,42.13,2914700.0,0.0,1.0,27.971868,28.954295,27.671682,28.742800,2914700.00,4.635108,2.756098
7,A,1999-11-30,42.00,42.94,40.94,42.19,3083000.0,0.0,1.0,28.654109,29.295415,27.930934,28.783735,3083000.00,4.885198,0.452381
8,A,1999-12-01,42.19,43.44,41.88,42.94,2115400.0,0.0,1.0,28.783735,29.636535,28.572240,29.295415,2115400.00,3.724928,1.777672
9,A,1999-12-02,43.75,45.00,43.19,44.13,2195900.0,0.0,1.0,29.848030,30.700831,29.465975,30.107281,2195900.00,4.190785,0.868571
10,A,1999-12-03,44.94,45.69,44.31,44.50,2175700.0,0.0,1.0,30.659896,31.171577,30.230085,30.359711,2175700.00,3.114421,-0.979083
11,A,1999-12-06,45.25,46.44,45.19,45.75,1610000.0,0.0,1.0,30.871391,31.683257,30.830457,31.212511,1610000.00,2.766099,1.104972
12,A,1999-12-07,45.75,46.00,44.31,45.25,1585100.0,0.0,1.0,31.212511,31.383072,30.230085,30.871391,1585100.00,3.814037,-1.092896
13,A,1999-12-08,45.25,45.63,44.81,45.19,1350400.0,0.0,1.0,30.871391,31.130643,30.571205,30.830457,1350400.00,1.829949,-0.132597
14,A,1999-12-09,45.25,45.94,45.25,45.81,1451400.0,0.0,1.0,30.871391,31.342137,30.871391,31.253446,1451400.00,1.524862,1.237569
15,A,1999-12-10,45.69,45.94,44.75,44.75,1190800.0,0.0,1.0,31.171577,31.342137,30.530271,30.530271,1190800.00,2.659218,-2.057343
16,A,1999-12-13,45.50,46.25,44.38,45.50,2875900.0,0.0,1.0,31.041951,31.553632,30.277842,31.041951,2875900.00,4.213610,0.000000
17,A,1999-12-14,45.38,45.38,42.06,43.00,1665900.0,0.0,1.0,30.960082,30.960082,28.695043,29.336350,1665900.00,7.893485,-5.244601
18,A,1999-12-15,42.00,42.31,41.00,41.69,2087100.0,0.0,1.0,28.654109,28.865603,27.971868,28.442614,2087100.00,3.195122,-0.738095
19,A,1999-12-16,42.00,48.00,42.00,47.25,1848300.0,0.0,1.0,28.654109,32.747553,28.654109,32.235872,1848300.00,14.285714,12.500000
20,A,1999-12-17,46.38,47.12,45.44,45.94,2652400.0,0.0,1.0,31.642323,32.147181,31.001017,31.342137,2652400.00,3.697183,-0.948685
21,A,1999-12-20,46.25,46.94,46.13,46.88,856100.0,0.0,1.0,31.553632,32.024378,31.471763,31.983443,856100.00,1.755907,1.362162
22,A,1999-12-21,46.69,46.69,46.00,46.63,1616200.0,0.0,1.0,31.853818,31.853818,31.383072,31.812883,1616200.00,1.500000,-0.128507
23,A,1999-12-22,46.63,47.56,46.31,47.56,1363200.0,0.0,1.0,31.812883,32.447367,31.594566,32.447367,1363200.00,2.699201,1.994424
24,A,1999-12-23,47.50,50.00,47.44,49.75,1544700.0,0.0,1.0,32.406433,34.112034,32.365498,33.941474,1544700.00,5.396290,4.736842
25,A,1999-12-27,49.94,53.19,49.56,52.81,1451800.0,0.0,1.0,34.071100,36.288382,33.811848,36.029131,1451800.00,7.324455,5.746896
26,A,1999-12-28,54.25,61.50,53.94,61.50,2546500.0,0.0,1.0,37.011557,41.957802,36.800063,41.957802,2546500.00,14.015573,13.364055
27,A,1999-12-29,63.00,79.06,62.94,72.00,7524000.0,0.0,1.0,42.981163,53.937949,42.940229,49.121329,7524000.00,25.611694,14.285714
28,A,1999-12-30,76.00,80.00,74.25,79.25,4771900.0,0.0,1.0,51.850292,54.579255,50.656371,54.067574,4771900.00,7.744108,4.276316
29,A,1999-12-31,79.50,79.94,76.25,77.31,1381400.0,0.0,1.0,54.238135,54.538320,52.020852,52.744027,1381400.00,4.839344,-2.754717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,AAN,1986-10-17,16.50,16.50,16.50,16.50,193.0,0.0,1.0,2.272637,2.272637,2.272637,2.272637,1302.75,0.000000,0.000000
9971,AAN,1986-10-20,16.62,16.75,16.62,16.75,24000.0,0.0,1.0,2.289166,2.307071,2.289166,2.307071,162000.00,0.782190,0.782190
9972,AAN,1986-10-21,16.50,16.50,16.50,16.50,400.0,0.0,1.0,2.272637,2.272637,2.272637,2.272637,2700.00,0.000000,0.000000
9973,AAN,1986-10-22,16.50,16.50,16.50,16.50,2993.0,0.0,1.0,2.272637,2.272637,2.272637,2.272637,20202.75,0.000000,0.000000
9974,AAN,1986-10-23,16.50,16.75,16.50,16.75,27200.0,0.0,1.0,2.272637,2.307071,2.272637,2.307071,183600.00,1.515152,1.515152
9975,AAN,1986-10-24,16.50,16.50,16.25,16.25,22993.0,0.0,1.0,2.272637,2.272637,2.238203,2.238203,155202.75,1.538462,-1.515152
9976,AAN,1986-10-27,15.75,15.75,15.75,15.75,4000.0,0.0,1.0,2.169336,2.169336,2.169336,2.169336,27000.00,0.000000,0.000000
9977,AAN,1986-10-28,16.00,16.00,16.00,16.00,193.0,0.0,1.0,2.203769,2.203769,2.203769,2.203769,1302.75,0.000000,0.000000
9978,AAN,1986-10-29,16.00,16.00,15.50,16.00,800.0,0.0,1.0,2.203769,2.203769,2.134902,2.203769,5400.00,3.225806,0.000000
9979,AAN,1986-10-30,16.00,16.00,16.00,16.00,193.0,0.0,1.0,2.203769,2.203769,2.203769,2.203769,1302.75,0.000000,0.000000
9980,AAN,1986-10-31,16.00,16.00,16.00,16.00,0.0,0.0,1.0,2.203769,2.203769,2.203769,2.203769,0.00,0.000000,0.000000
9981,AAN,1986-11-03,16.00,16.00,16.00,16.00,0.0,0.0,1.0,2.203769,2.203769,2.203769,2.203769,0.00,0.000000,0.000000
9982,AAN,1986-11-04,16.00,16.00,16.00,16.00,0.0,0.0,1.0,2.203769,2.203769,2.203769,2.203769,0.00,0.000000,0.000000
9983,AAN,1986-11-05,15.75,15.75,15.75,15.75,400.0,0.0,1.0,2.169336,2.169336,2.169336,2.169336,2700.00,0.000000,0.000000
9984,AAN,1986-11-06,15.25,15.25,15.00,15.00,1200.0,0.0,1.0,2.100468,2.100468,2.066034,2.066034,8100.00,1.666667,-1.639344
9985,AAN,1986-11-07,15.00,15.50,14.75,15.00,1102993.0,0.0,1.0,2.066034,2.134902,2.031600,2.066034,7445202.75,5.084746,0.000000
9986,AAN,1986-11-10,15.00,15.25,15.00,15.00,30193.0,0.0,1.0,2.066034,2.100468,2.066034,2.066034,203802.75,1.666667,0.000000
9987,AAN,1986-11-11,15.00,15.25,15.00,15.00,6593.0,0.0,1.0,2.066034,2.100468,2.066034,2.066034,44502.75,1.666667,0.000000
9988,AAN,1986-11-12,15.00,15.25,15.00,15.25,3793.0,0.0,1.0,2.066034,2.100468,2.066034,2.100468,25602.75,1.666667,1.666667
9989,AAN,1986-11-13,15.00,15.00,15.00,15.00,6593.0,0.0,1.0,2.066034,2.066034,2.066034,2.066034,44502.75,0.000000,0.000000
9990,AAN,1986-11-14,15.00,15.25,14.50,14.50,18400.0,0.0,1.0,2.066034,2.100468,1.997166,1.997166,124200.00,5.172414,-3.333333
9991,AAN,1986-11-17,14.50,14.75,14.50,14.50,14593.0,0.0,1.0,1.997166,2.031600,1.997166,1.997166,98502.75,1.724138,0.000000
9992,AAN,1986-11-18,14.50,14.50,14.25,14.25,35200.0,0.0,1.0,1.997166,1.997166,1.962732,1.962732,237600.00,1.754386,-1.724138
9993,AAN,1986-11-19,14.25,14.25,14.00,14.00,43793.0,0.0,1.0,1.962732,1.962732,1.928298,1.928298,295602.75,1.785714,-1.754386
9994,AAN,1986-11-20,14.00,14.50,14.00,14.50,66193.0,0.0,1.0,1.928298,1.997166,1.928298,1.997166,446802.75,3.571429,3.571429
9995,AAN,1986-11-21,14.50,14.50,14.00,14.00,50993.0,0.0,1.0,1.997166,1.997166,1.928298,1.928298,344202.75,3.571429,-3.448276
9996,AAN,1986-11-24,14.25,15.00,14.25,14.87,73793.0,0.0,1.0,1.962732,2.066034,1.962732,2.048128,498102.75,5.263158,4.350877
9997,AAN,1986-11-25,14.87,15.25,14.50,14.50,511600.0,0.0,1.0,2.048128,2.100468,1.997166,1.997166,3453300.00,5.172414,-2.488231
9998,AAN,1986-11-26,14.50,15.25,14.50,14.75,30593.0,0.0,1.0,1.997166,2.100468,1.997166,2.031600,206502.75,5.172414,1.724138
9999,AAN,1986-11-28,15.00,15.75,15.00,15.25,88800.0,0.0,1.0,2.066034,2.169336,2.066034,2.100468,599400.00,5.000000,1.666667

In [32]:
df_features=data_csv[['adj_open','adj_close','adj_high','adj_low','adj_volume']]
df=data_csv[['adj_close','h-l_%','%_chng','adj_volume']]  # only this is used as features not data_csv
#data_csv=data_csv.drop(['date','ticker'],1)
#data_csv.drop(inplace=True)
data_csv.head(6)

,ticker,date,open,high,low,close,volume,ex-dividend,split_ratio,adj_open,adj_high,adj_low,adj_close,adj_volume,h-l_%,%_chng
0,A,1999-11-18,45.50,50.00,40.00,44.00,44739900.0,0.0,1.0,31.041951,34.112034,27.289627,30.018590,44739900.0,25.000000,-3.296703
1,A,1999-11-19,42.94,43.00,39.81,40.38,10897100.0,0.0,1.0,29.295415,29.336350,27.160002,27.548879,10897100.0,8.013062,-5.961807
2,A,1999-11-22,41.31,44.00,40.06,44.00,4705200.0,0.0,1.0,28.183363,30.018590,27.330562,30.018590,4705200.0,9.835247,6.511740
3,A,1999-11-23,42.50,43.63,40.25,40.25,4274400.0,0.0,1.0,28.995229,29.766161,27.460188,27.460188,4274400.0,8.397516,-5.294118
4,A,1999-11-24,40.13,41.94,40.00,41.06,3464400.0,0.0,1.0,27.378319,28.613174,27.289627,28.012803,3464400.0,4.850000,2.317468
5,A,1999-11-26,40.88,41.50,40.75,41.19,1237100.0,0.0,1.0,27.889999,28.312988,27.801308,28.101494,1237100.0,1.840491,0.758317

In [33]:
df.head(6)

   adj_close      h-l_%    %_chng  adj_volume
0  30.018590  25.000000 -3.296703  44739900.0
1  27.548879   8.013062 -5.961807  10897100.0
2  30.018590   9.835247  6.511740   4705200.0
3  27.460188   8.397516 -5.294118   4274400.0
4  28.012803   4.850000  2.317468   3464400.0
5  28.101494   1.840491  0.758317   1237100.0

In [34]:
print (data_csv.shape)
print (len(data_csv))
print(0.1*(len(data_csv)))

(10000, 16)
10000
1000.0

In [35]:
import math

In [36]:
#we wan to predict todays adj_close from previous 10% entries in adj_close
df.fillna(-9999,inplace=True)
forecast_col='adj_close'

forecast_out=int(math.ceil(0.001*(len(df))))
print (forecast_out)

df['label']=df[forecast_col].shift(-forecast_out)

10

/home/ishaan/Softwares/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3035: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)
/home/ishaan/Softwares/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [37]:
#df_temp=data_csv[['adj_open','adj_close','adj_high','adj_low','adj_volume','label']]
#df_temp[['adj_close','label']].head(101)
#we can see by shift we shifted adjclose up by 100 and stored it in label column
#we are comparing forcast price to adj_close price---- main 
#data_csv

In [38]:
import numpy as np

In [39]:
#x--features   y---labels

x=np.array(df.drop(['label'],1))
x_lately=x[-forecast_out:]
x=x[:-forecast_out]

df.dropna(inplace=True)
y=np.array(df['label'])

x=preprocessing.scale(x)

#actually we are comparing adj_close to label

/home/ishaan/Softwares/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [40]:

df

      adj_close      h-l_%     %_chng   adj_volume      label
0     30.018590  25.000000  -3.296703  44739900.00  30.359711
1     27.548879   8.013062  -5.961807  10897100.00  31.212511
2     30.018590   9.835247   6.511740   4705200.00  30.871391
3     27.460188   8.397516  -5.294118   4274400.00  30.830457
4     28.012803   4.850000   2.317468   3464400.00  31.253446
5     28.101494   1.840491   0.758317   1237100.00  30.530271
6     28.742800   4.635108   2.756098   2914700.00  31.041951
7     28.783735   4.885198   0.452381   3083000.00  29.336350
8     29.295415   3.724928   1.777672   2115400.00  28.442614
9     30.107281   4.190785   0.868571   2195900.00  32.235872
10    30.359711   3.114421  -0.979083   2175700.00  31.342137
11    31.212511   2.766099   1.104972   1610000.00  31.983443
12    30.871391   3.814037  -1.092896   1585100.00  31.812883
13    30.830457   1.829949  -0.132597   1350400.00  32.447367
14    31.253446   1.524862   1.237569   1451400.00  33.941474
15    30.530271   2.659218  -2.057343   1190800.00  36.029131
16    31.041951   4.213610   0.000000   2875900.00  41.957802
17    29.336350   7.893485  -5.244601   1665900.00  49.121329
18    28.442614   3.195122  -0.738095   2087100.00  54.067574
19    32.235872  14.285714  12.500000   1848300.00  52.744027
20    31.342137   3.697183  -0.948685   2652400.00  49.121329
21    31.983443   1.755907   1.362162    856100.00  45.369006
22    31.812883   1.500000  -0.128507   1616200.00  41.998737
23    32.447367   2.699201   1.994424   1363200.00  40.934441
24    33.941474   5.396290   4.736842   1544700.00  44.345645
25    36.029131   7.324455   5.746896   1451800.00  47.033673
26    41.957802  14.015573  13.364055   2546500.00  46.392367
27    49.121329  25.611694  14.285714   7524000.00  45.457697
28    54.067574   7.744108   4.276316   4771900.00  46.139938
29    52.744027   4.839344  -2.754717   1381400.00  46.651618
...         ...        ...        ...          ...        ...
9960   2.272637   1.515152  -1.492537    218700.00   2.272637
9961   2.341505   0.000000   0.000000      4002.75   2.307071
9962   2.341505   0.000000   0.000000         0.00   2.272637
9963   2.238203   0.000000   0.000000     21600.00   2.272637
9964   2.272637   0.000000   0.000000     33702.75   2.307071
9965   2.272637   3.030303   0.000000   1414800.00   2.238203
9966   2.272637   1.515152   0.000000     16200.00   2.169336
9967   2.307071   3.076923   1.515152    162000.00   2.203769
9968   2.307071   1.492537   0.000000    205200.00   2.203769
9969   2.307071   0.000000   0.000000         0.00   2.203769
9970   2.272637   0.000000   0.000000      1302.75   2.203769
9971   2.307071   0.782190   0.782190    162000.00   2.203769
9972   2.272637   0.000000   0.000000      2700.00   2.203769
9973   2.272637   0.000000   0.000000     20202.75   2.169336
9974   2.307071   1.515152   1.515152    183600.00   2.066034
9975   2.238203   1.538462  -1.515152    155202.75   2.066034
9976   2.169336   0.000000   0.000000     27000.00   2.066034
9977   2.203769   0.000000   0.000000      1302.75   2.066034
9978   2.203769   3.225806   0.000000      5400.00   2.100468
9979   2.203769   0.000000   0.000000      1302.75   2.066034
9980   2.203769   0.000000   0.000000         0.00   1.997166
9981   2.203769   0.000000   0.000000         0.00   1.997166
9982   2.203769   0.000000   0.000000         0.00   1.962732
9983   2.169336   0.000000   0.000000      2700.00   1.928298
9984   2.066034   1.666667  -1.639344      8100.00   1.997166
9985   2.066034   5.084746   0.000000   7445202.75   1.928298
9986   2.066034   1.666667   0.000000    203802.75   2.048128
9987   2.066034   1.666667   0.000000     44502.75   1.997166
9988   2.100468   1.666667   1.666667     25602.75   2.031600
9989   2.066034   0.000000   0.000000     44502.75   2.100468

[9990 rows x 5 columns]

In [41]:
#x=x[:-forecast_out]
print (len(x),len(y))

9990 9990

In [42]:

from sklearn.linear_model import LinearRegression

In [43]:
x_train,x_test,y_train,y_test=cross_validation.train_test_split(x,y,test_size=0.3)

In [44]:
clf=LinearRegression()
clf.fit(x_train,y_train)
accuracy=clf.score(x_test,y_test)
predict_accuracy=clf.predict(x_lately)  # how does classifier knows to return value in list or any other data structure?

In [45]:
clf2=svm.SVR()
clf2.fit(x_train,y_train)
accuracy2=clf2.score(x_test,y_test)

In [46]:
print(accuracy)   #why on 60% accuracy?
print (accuracy2)
print (predict_accuracy)
print (predict_accuracy.shape)

0.9658727188812586
0.2569022599975451
[  -45605.11231413   -36096.37882665   -87550.00109596  -109008.0036997
  -164918.17206251  -126985.63632566  -183885.21420301 -1276925.43055764
   -76036.85852543  -221346.77182077]
(10,)

In [47]:
#create graph  with given date values and one without
#use style
#cannot understand the reason given behind calculaion of date so next ime review video 6 of sentdex.